// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (8080, config = {host: "localhost"});

service / on ep0 {
    # Delete a programme
    #
    # + programmeCode - Unique identifier for the programme.
    # + return - returns can be any of following types 
    # http:NoContent (Programme deleted successfully.)
    # http:NotFound (Programme not found.)
    resource function delete programmes/[string programmeCode]() returns http:NoContent|http:NotFound {
    }

    # Retrieve all programmes
    #
    # + return - A list of programmes. 
    resource function get programmes() returns Programme[] {
    }

    # Retrieve a specific programme
    #
    # + programmeCode - Unique identifier for the programme.
    # + return - returns can be any of following types 
    # http:Ok (Programme details.)
    # http:NotFound (Programme not found.)
    resource function get programmes/[string programmeCode]() returns Programme|http:NotFound {
    }

    # Retrieve programmes by faculty
    #
    # + facultyName - Name of the faculty.
    # + return - A list of programmes belonging to the specified faculty. 
    resource function get programmes/faculty/[string facultyName]() returns Programme[] {
    }

    # Retrieve programmes due for review
    #
    # + return - A list of programmes due for review. 
    resource function get programmes/review() returns Programme[] {
    }

    # Add a new programme
    #
    # + return - returns can be any of following types 
    # http:Created (Programme created successfully.)
    # http:BadRequest (Invalid input.)
    resource function post programmes(@http:Payload Programme payload) returns http:Created|http:BadRequest {
    }

    # Update an existing programme
    #
    # + programmeCode - Unique identifier for the programme.
    # + return - returns can be any of following types 
    # http:Ok (Programme updated successfully.)
    # http:BadRequest (Invalid input.)
    # http:NotFound (Programme not found.)
    resource function put programmes/[string programmeCode](@http:Payload Programme payload) returns http:Ok|http:BadRequest|http:NotFound {
    }
}
