// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
map<Programme> programme = {};

listener http:Listener ep0 = new (8080, config = {host: "localhost"});

service / on ep0 {
    # Delete a programme
    #
    # + programmeCode - Unique identifier for the programme.
    # + return - returns can be any of following types 
    # http:NoContent (Programme deleted successfully.)
    # http:NotFound (Programme not found.)
    # Retrieve all programmes
    #
    # + return - A list of programmes. 
    resource function delete programmes/[string programmeCode]() returns http:NoContent|http:NotFound {
        Programme? prog = programme[programmeCode.toString()];

        if prog is () {
            return <http:NotFound>{body: "Programme not found"};
        }

        _ = programme.remove(programmeCode.toString());
        return <http:NoContent>{};
    }

    # Retrieve all programmes
    #
    # + return - A list of programmes. 
    resource function get programmes() returns Programme[]|http:NotFound {
        Programme[] prog = programme.toArray();
        if prog.length() == 0 {
            return <http:NotFound>{body: "Programme not found"};
        }
        return prog;
    }

    # Retrieve a specific programme
    #
    # + programmeCode - Unique identifier for the programme.
    # + return - returns can be any of following types 
    # http:Ok (Programme details.)
    # http:NotFound (Programme not found.)
    resource function get programmes/[string programmeCode]() returns Programme|http:NotFound {
        Programme? prog = programme[programmeCode.toString()];
        if prog is () {
            return <http:NotFound>{body: "Programme not found"};
        }
        return prog;
    }

    # Retrieve programmes by faculty
    #
    # + faculty - Name of the faculty.
    # + return - A list of programmes belonging to the specified faculty. 
    resource function get programmes/faculty/[string faculty]() returns Programme[]|http:NotFound {
        Programme[] prog = programme.toArray().filter(p => p.faculty == faculty);
        if prog.length() == 0 {
            return <http:NotFound>{body: "Programme not found in faculty"};
        }
        return prog;
    }

    # Retrieve programmes due for review
    #
    # + return - A list of programmes due for review. 
    resource function get programmes/review() returns Programme[]|http:NotFound {
        Programme[] prog = programme.toArray();
        if prog.length() == 0 {
            return <http:NotFound>{body: "Programme review not found"};
        }
        return prog;
    }

    # Add a new programme
    #
    # + return - returns can be any of following types 
    # http:Created (Programme created successfully.)
    # http:BadRequest (Invalid input.)
    resource function post programmes(@http:Payload Programme payload) returns http:Created|http:BadRequest {
        if (payload.programmeCode is () || payload.nqfLevel is () || payload.faculty is () || payload.department is () || payload.title is () || payload.registrationDate is () || payload.courses is ()) {
            return <http:BadRequest>{body: "All fields (id, name, age, course) are required"};
        }

        programme[payload.programmeCode.toString()] = payload;
        return <http:Created>{body: "Programme created successfully", headers: {"Location": "/Programme/" + payload.programmeCode.toString()}};
    }

    # Update an existing programme
    #
    # + programmeCode - Unique identifier for the programme.
    # + return - returns can be any of following types 
    # http:Ok (Programme updated successfully.)
    # http:BadRequest (Invalid input.)
    # http:NotFound (Programme not found.)
    resource function put programmes/[string programmeCode](@http:Payload Programme payload) returns http:Ok|http:BadRequest|http:NotFound {
        Programme? prog = programme[programmeCode.toString()];
        if prog is () {
            return <http:NotFound>{body: "Programme not found"};
        }

        if (payload.programmeCode is () || payload.nqfLevel is () || payload.faculty is () || payload.department is () || payload.title is () || payload.registrationDate is () || payload.courses is ()) {
            return <http:BadRequest>{body: "All fields (id, name, age, course) are required"};
        }

        prog.nqfLevel = payload.nqfLevel;
        prog.faculty = payload.faculty;
        prog.department = payload.department;
        prog.title = payload.title;
        prog.registrationDate = payload.registrationDate;
        prog.courses = payload.courses;
        programme[programmeCode.toString()] = prog;

        return <http:Ok>{body: "Programme updated successfully"};
    }
}

